[package]
name = "i1db"
version = "0.1.0"
authors = ["Ivan Sorokin <ivan@sorokin.io>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rust-crypto = "0.2.36"
rand = "0.7.0"
hex = "0.3.2"
